name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: g++ pkg-config libx11-dev libasound2-dev libudev-dev
        version: 1.0
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
